CREATE DATABASE IF NOT EXISTS todolist CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE todolist;

DROP TABLE IF EXISTS `todolist`;
CREATE TABLE `todolist` (
    `AutoID` INT NOT NULL AUTO_INCREMENT COMMENT '事项ID',
    `Title` VARCHAR(200) NOT NULL COMMENT '事项标题',
    `Status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态',
    `DateTime` DATETIME NULL COMMENT '完成日期',
    `IsDelete` TINYINT NOT NULL DEFAULT 0 COMMENT '软删除标记',
    `CreateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UpdateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`AutoID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(64) NOT NULL UNIQUE,
    `password_hash` VARCHAR(128) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `IsDelete` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
